name: deploy
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # Option 1: Workload Identity Federation
          #workload_identity_provider: 'projects/960889850908/locations/global/wo...'
          #service_account: 'service-key-for-pr-coding@pr-coding-cicd.iam.gservic...'
          # Option 2: Service Account Key (less recommended for production)
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Inject Secret Key
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
            FIREBASE_KEY:projects/960889850908/secrets/FIREBASE_KEY/versions/2
          export_to_environment: true
          #secrets: projects/PROJECT_NUMBER/secrets/MY_SECRET_NAME/versions/latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: express-practice
          image: ${{ secrets.DOCKER_USERNAME }}/express-practice:latest
          region: asia-northeast3 # Replace with your Cloud Run region